package:
  name: py3-cython
  version: 3.0.10
  epoch: 2
  description: Cython is an optimising static compiler for both the Python & the extended Cython programming languages.
  copyright:
    - license: Apache-2.0
  dependencies:
    provider-priority: 0

vars:
  pypi-package: cython

data:
  - name: py-versions
    items:
      3.10: "310"
      3.11: "311"
      3.12: "312"

environment:
  contents:
    packages:
      - build-base
      - busybox
      - py3-supported-pip
      - py3-supported-python-dev
      - py3-supported-wheel

pipeline:
  - uses: fetch
    with:
      expected-sha256: 00f97476cef9fcd9a89f9d2a49be3b518e1a74b91f377fe08c97fcb44bc0f7d7
      uri: https://github.com/cython/cython/archive/${{package.version}}.tar.gz

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}-base
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - ${{package.name}}
        - cython
    pipeline:
      - uses: py/pip-build-install-bootstrap
        with:
          python: python${{range.key}}
      - uses: strip

  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: Executable binaries for ${{vars.pypi-package}} installed for python${{range.key}}
    dependencies:
      runtime:
        - py${{range.key}}-${{vars.pypi-package}}-base
      provides:
        - py3-${{vars.pypi-package}}
      provider-priority: ${{range.value}}
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/usr/bin
          mv ${{targets.contextdir}}/../py${{range.key}}-${{vars.pypi-package}}-base/usr/bin/cygdb ${{targets.contextdir}}/usr/bin/cygdb${{range.key}}
          mv ${{targets.contextdir}}/../py${{range.key}}-${{vars.pypi-package}}-base/usr/bin/cython ${{targets.contextdir}}/usr/bin/cythonize${{range.key}}
          mv ${{targets.contextdir}}/../py${{range.key}}-${{vars.pypi-package}}-base/usr/bin/cythonize ${{targets.contextdir}}/usr/bin/cythonize${{range.key}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.12-${{vars.pypi-package}}
        - py3.11-${{vars.pypi-package}}
        - py3.10-${{vars.pypi-package}}

update:
  enabled: true
  github:
    identifier: cython/cython
