package:
  name: py3-versioneer
  version: "0.29"
  epoch: 6
  description: Easy VCS-based management of project version strings
  copyright:
    - license: 'Unlicense'
  dependencies:
    provider-priority: 0

vars:
  pypi-package: versioneer

data:
  - name: py-versions
    items:
      3.10: "310"
      3.11: "311"
      3.12: "312"

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-supported-gpep517
      - py3-supported-setuptools
      - py3-supported-pip
      - py3-supported-wheel
      - py3-supported-python-dev
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/python-versioneer/python-versioneer
      tag: ${{package.version}}
      expected-commit: 28c613dbef5fce09dc3ba6b1baa811c2d76b2245

subpackages:
  - range: py-versions
    # Historically py3.X-pip installed /usr/bin/pip
    # Hence co-installable modules only package is called -base
    # And /usr/bin/pip conflicting package is called py3.X-versioneer
    name: py${{range.key}}-${{vars.pypi-package}}-base
    description: ${{vars.pypi-package}} installed for python${{range.key}}
    pipeline:
      - runs: python${{range.key}} setup.py clean --all
      - uses: py/pip-build-install-bootstrap
        with:
          python: python${{range.key}}

  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: Executable binaries for ${{vars.pypi-package}} installed for python${{range.key}}
    dependencies:
      runtime:
        - py${{range.key}}-${{vars.pypi-package}}-base
      provides:
        - py3-${{vars.pypi-package}}
      provider-priority: ${{range.value}}
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/usr/bin
          mv ${{targets.contextdir}}/../py${{range.key}}-${{vars.pypi-package}}-base/usr/bin/versioneer ${{targets.contextdir}}/usr/bin/versioneer${{range.key}}

      - uses: strip

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}
        - py3.11-${{vars.pypi-package}}
        - py3.12-${{vars.pypi-package}}

update:
  enabled: true
  release-monitor:
    identifier: 221177
